# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160604_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 5, 16, 31, 46, 374730, tzinfo=utc), verbose_name='Date de parution'),
            preserve_default=False,
        ),
    ]
